---
- name: Converge
  hosts: all
  vars:
    atl_product_family: "bitbucket"
    atl_product_edition: "bitbucket"
    atl_product_user: "bitbucket"
    atl_product_version: "6.3.1"

    atl_jdbc_user: 'bb_db_user'
    atl_jdbc_password: 'molecule_password'

  roles:
    - role: linux_common
    - role: product_common
    - role: product_install
    - role: bitbucket_config
